// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAPI.Models;

#nullable disable

namespace SchoolAPI.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251006193511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolAPI.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Najwa Sokkri",
                            Name = "ENISo",
                            Rating = 3.5,
                            Sections = "IA, GTE, GMP, MECA, EI",
                            WebSite = "https://eniso.rnu.tn/"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Mohsen Abid",
                            Name = "ENIM",
                            Rating = 3.2999999999999998,
                            Sections = "Textile, Mécanique, Electronique, Energitique",
                            WebSite = "https://enim.rnu.tn/"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Yosri Farhat",
                            Name = "ENICAR",
                            Rating = 3.3999999999999999,
                            Sections = "Infotronique, Informatique, Mecatronique"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
